"""empty message

Revision ID: 55f619b00f23
Revises: b99c72b299c8
Create Date: 2021-11-22 20:24:34.218380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f619b00f23'
down_revision = 'b99c72b299c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('films_user_added_fkey', 'films', type_='foreignkey')
    op.create_foreign_key(None, 'films', 'users', ['user_added'], ['id'])
    op.add_column('users', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_column('users', 'id')
    op.drop_constraint(None, 'films', type_='foreignkey')
    op.create_foreign_key('films_user_added_fkey', 'films', 'users', ['user_added'], ['id'])
    # ### end Alembic commands ###
