"""empty message

Revision ID: b99c72b299c8
Revises: 
Create Date: 2021-11-20 18:15:56.171705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99c72b299c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films_directors',
    sa.Column('films_film_id', sa.Integer(), nullable=True),
    sa.Column('directors_director_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['directors_director_id'], ['directors.director_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['films_film_id'], ['films.film_id'], ondelete='CASCADE')
    )
    op.create_table('films_genres',
    sa.Column('films_film_id', sa.Integer(), nullable=True),
    sa.Column('genres_genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['films_film_id'], ['films.film_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genres_genre_id'], ['genres.genre_id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('films_genres')
    op.drop_table('films_directors')
    # ### end Alembic commands ###
