"""empty message

Revision ID: d69f6b28df26
Revises: c78a4240268d
Create Date: 2021-11-11 15:00:39.896609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69f6b28df26'
down_revision = 'c78a4240268d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors',
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('second_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('director_id'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('second_name')
    )
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('genre_id'),
    sa.UniqueConstraint('genre')
    )
    op.create_table('rateds',
    sa.Column('rated_id', sa.Integer(), nullable=False),
    sa.Column('rated', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('rated_id'),
    sa.UniqueConstraint('rated')
    )
    op.create_table('films',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(length=10), nullable=True),
    sa.Column('film_name', sa.Text(), nullable=False),
    sa.Column('rateds_rated_id', sa.Integer(), nullable=False),
    sa.Column('poster_url', sa.Text(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_added', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rateds_rated_id'], ['rateds.rated_id'], ),
    sa.ForeignKeyConstraint(['user_added'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('film_id'),
    sa.UniqueConstraint('imdb_id'),
    sa.UniqueConstraint('poster_url')
    )
    op.create_index(op.f('ix_films_description'), 'films', ['description'], unique=False)
    op.create_index(op.f('ix_films_film_name'), 'films', ['film_name'], unique=False)
    op.create_index(op.f('ix_films_rating'), 'films', ['rating'], unique=False)
    op.create_index(op.f('ix_films_release_date'), 'films', ['release_date'], unique=False)
    op.create_table('films_directors',
    sa.Column('films_film_id', sa.Integer(), nullable=True),
    sa.Column('directors_director_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['directors_director_id'], ['directors.director_id'], ),
    sa.ForeignKeyConstraint(['films_film_id'], ['films.film_id'], )
    )
    op.create_table('films_genres',
    sa.Column('films_film_id', sa.Integer(), nullable=True),
    sa.Column('genres_genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['films_film_id'], ['films.film_id'], ),
    sa.ForeignKeyConstraint(['genres_genre_id'], ['genres.genre_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('films_genres')
    op.drop_table('films_directors')
    op.drop_index(op.f('ix_films_release_date'), table_name='films')
    op.drop_index(op.f('ix_films_rating'), table_name='films')
    op.drop_index(op.f('ix_films_film_name'), table_name='films')
    op.drop_index(op.f('ix_films_description'), table_name='films')
    op.drop_table('films')
    op.drop_table('rateds')
    op.drop_table('genres')
    op.drop_table('directors')
    # ### end Alembic commands ###
